# dvc.yaml - Pipeline reproducible TelcoVision

stages:
  prepare:
    cmd: python src/data_prep.py --input data/raw/telco_churn.csv --output data/processed --params params.yaml
    deps:
      - src/data_prep.py
      - data/raw/telco_churn.csv
      - params.yaml
    params:
      - data_prep
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - data/processed/metadata.json

  train:
    cmd: python src/train.py --data data/processed --model models/model.joblib --metrics metrics.json --params params.yaml
    deps:
      - src/train.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - params.yaml
    params:
      - train
    outs:
      - models/model.joblib
      - metrics.json

  evaluate:
    cmd: python src/evaluate.py --data data/processed --model models/model.joblib --output evaluation
    deps:
      - src/evaluate.py
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - models/model.joblib
    outs:
      - evaluation/confusion_matrix.png
      - evaluation/roc_curve.png
      - evaluation/precision_recall_curve.png
      - evaluation/classification_report.txt
      - evaluation/classification_report.json
      - evaluation/advanced_metrics.json