# params.yaml - Parametros del Pipeline TelcoVision

# Preparación de datos
data_prep:
  test_size: 0.2
  random_state: 42
  target_column: churn
  id_column: customer_id

  # Columnas numéricas
  numeric_features:
    - age
    - tenure_months
    - monthly_charges
    - total_charges
  
  categorical_features:
    - gender
    - region
    - contract_type
    - internet_service
    - phone_service
    - multiple_lines
    - payment_method

train:
  model_type: random_forest
  
  random_forest:
    n_estimators: 200
    max_depth: 20
    min_samples_split: 5
    min_samples_leaf: 1
    random_state: 42
  
  logistic_regression:
    C: 1.0
    max_iter: 1000
    solver: 'lbfgs'
    random_state: 42
  
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - roc_auc